### ISSUE TITLE
Information Request

### ISSUE THREAD

**Issue by diannevolek** [backdrop-contrib/feef#1]
Please can you tell me if this placeholder [file-embed:7] can only be used in a WISIWYG editor, or if it could be used in a text field.

I am trying to link specification drawings to product parts (a content type).  The same 100 drawings are linked to 5000 parts. I've been trying to work out how to include the file more as a reference than a .pdf location.

**Comment by indigoxela** [comment]
Hi @diannevolek,

the filter does work without using a WISIWYG editor. You have to know the file id's, of course, as there's no widget without the editor.

Two things are important:

1. It has to be a "filtered format", anything you can configure on /admin/config/content/formats
2. The filter has to be turned on

![filter-turned-on](https://user-images.githubusercontent.com/842066/147121581-7b63dc1a-2c19-43cd-ab32-209145f7e124.png)

Does that help?

**Comment by diannevolek** [comment]
Thank you!
