### ISSUE TITLE
UI does not find any entity file

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/feef#2]
After installing and enabling the module and input filter I've tried to embed an existing file (pdf org jpg) within a text area. But the module does not find any match. The files are used in core and paragraph fields and I'm logged in as the system admin.

**Comment by indigoxela** [comment]
Can you please check the content filter settings on your text fields?

Which format? Does the format have the "File Entity Embed Filter" enabled, anyway? Just enabling the module isn't supposed to do anything on its own, as you need to enable the corresponding "output" filter to get the result.

Your report is a bit sparse. Can you provide the format settings and what the actual output is?

And by the way "Thing not working" is the most demotivating and least informative issue title in open source projects. :grin:

**Comment by djzwerg** [comment]
I'm using full_html. Adding `[file-embed:fid]` manually works but the UI does not find anything.

**Comment by indigoxela** [comment]
> ... full_html

Hm, but with CKEditor enabled?

> Adding [file-embed:fid] manually works

So the base functionality is fully there...

> ... the UI does not find anything.

Check the view on /admin/structure/views/view/feef_autocomplete and compare that to the File Entities, you're trying to embed. Is it /admin/structure/file-types/manage/document (Document) or are you using a custom file type.

If the latter, you have to adapt the view.

**Comment by indigoxela** [comment]
From the official documentation (see the README):

> By default this modules' autocomplete plugin filters for audio and video file entities on your server. To include additional file types, you can edit the view (feef_autocomplete).

![read-the-docs](https://user-images.githubusercontent.com/842066/210060790-828e01d7-6ae6-4296-89a5-b684a5ecf857.png)

**Comment by djzwerg** [comment]
OMG thanks a lot @indigoxela ! I read over that part. Sorry! I wish you a happy new year!
